global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "telco-churn-render-api"
    metrics_path: "/metrics"
    scheme: https
    static_configs:
      - targets:
          - "mlops-champion-challenger.onrender.com"
